name: izmir_taksi
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #Uİ
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_spinkit: ^5.2.1
  motion_tab_bar: ^2.0.4
  gap: ^3.0.1
  cupertino_icons: ^1.0.6
  #STATE MANAGEMENT
  flutter_bloc:
  provider: ^6.1.2
  #POSTAPI
  dio: ^5.5.0+1
  #OTHER
  geolocator: ^8.0.3
  google_maps_flutter: ^2.1.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


  assets:
  - assets/
  - assets/animation/

